
version: '3'

networks:
    front:
# swarm usage:
        # driver: overlay
# non-cluster usage:
        #driver: bridge
# with custom 'front' bridge configured on host
         # external: true
         ipam:
             driver: default
             config:
                 - subnet: 10.0.142.0/24


services:
    nginx:
        build: build/nginx
        container_name: ${COMPOSE_PROJECT_NAME:-chall}-nginx
        hostname: ${COMPOSE_PROJECT_NAME:-chall}-nginx
        ports:
            - 127.0.0.1:5005:80/tcp
        networks:
            front:
                  ipv4_address: 10.0.142.10
        restart: always
        volumes:
            - ${ROOT:-.}/data/www/bin:/var/www/html/bin:ro
            - ${ROOT:-.}/data/www/config:/var/www/html/config:ro
            - ${ROOT:-.}/data/www/public:/var/www/html/public:ro
            - ${ROOT:-.}/data/www/src:/var/www/html/src:ro
            - ${ROOT:-.}/data/www/templates:/var/www/html/templates:ro
            - ${ROOT:-.}/data/www/tests:/var/www/html/tests:ro
            - ${ROOT:-.}/data/www/translations:/var/www/html/translations:ro
            - ${ROOT:-.}/data/www/.env:/var/www/html/.env:ro
            - ${ROOT:-.}/data/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        links:
            - php
            - flask
    flask:
      build: './build/flask'
      container_name: ${COMPOSE_PROJECT_NAME:-chall}-flask
      hostname: ${COMPOSE_PROJECT_NAME:-chall}-flask
      ports:
            - 127.0.0.1:5001:5001/tcp
      networks:
          front:
              ipv4_address: 10.0.142.20
      volumes:
            - ${ROOT:-.}/data/flask/app.py:/app/app.py:ro
      links:
            - mysql
    php:
        build: build/php
        image: php:8-fpm-alpine
        container_name: ${COMPOSE_PROJECT_NAME:-chall}-php
        hostname: ${COMPOSE_PROJECT_NAME:-chall}-php
        networks:
            front:
                    ipv4_address: 10.0.142.2
        restart: always
        volumes:
            - ${ROOT:-.}/data/www/bin:/var/www/html/bin:ro
            - ${ROOT:-.}/data/www/config:/var/www/html/config:ro
            - ${ROOT:-.}/data/www/public:/var/www/html/public:rw
            - ${ROOT:-.}/data/www/src/Kernel.php:/var/www/html/src/Kernel.php:ro
            - ${ROOT:-.}/data/www/src/Controller:/var/www/html/src/Controller:rw
            - ${ROOT:-.}/data/www/src/Entity:/var/www/html/src/Entity:rw
            - ${ROOT:-.}/data/www/src/Repository:/var/www/html/src/Repository:rw
            - ${ROOT:-.}/data/www/src/Service:/var/www/html/src/Service:ro
            - ${ROOT:-.}/data/www/templates:/var/www/html/templates:rw
            - ${ROOT:-.}/data/www/tests:/var/www/html/tests:ro
            - ${ROOT:-.}/data/www/translations:/var/www/html/translations:ro
            - ${ROOT:-.}/data/www/.env:/var/www/html/.env:ro
        links:
            - mysql
            - flask
        # Automates the initiation of the symfony database inside the containers
        command: sh -c "sh -c 'sleep 10 && cd /var/www/html && /usr/local/bin/php bin/console make:migration && php bin/console doctrine:migrations:migrate && php bin/console doctrine:fixtures:load -q &' && exec php-fpm -F -R"
        
    mysql:
      build: './build/mysql/'
      container_name: ${COMPOSE_PROJECT_NAME:-chall}-mysql
      hostname: ${COMPOSE_PROJECT_NAME:-chall}-mysql
      networks:
          front:
               ipv4_address: 10.0.142.7
      restart: always
      platform: linux/amd64
      image: mysql:5.7
      environment:
        - MYSQL_DATABASE=db_public
        - MYSQL_RANDOM_ROOT_PASSWORD=true
      ulimits:
        nofile:
            soft: 20000
            hard: 40000


